cover_ratio: 0.3433220411033006
dataset_path: ./datasets/nvGesture
depth_ckp_model_path: null
depth_x: 224
depth_y: 224
dropout_prob: 0.15749658329901223
epoch: 100
frame_jump: 2
img_x: 224
img_y: 224
lambda: 0.05
learning_rate: 0.001
only_with_gesture: true
rgb_ckp_model_path: null
sample_duration: 64
tb_batch_freq: 100
train_annotation_path: ./datasets/nvGesture/nvgesture_train_correct_cvpr2016_v2.lst
train_batch_size: 12
train_num_of_workers: 10
train_shuffle_data: true
used_classes:
- 10
- 14
val_annotation_path: ./datasets/nvGesture/nvgesture_test_correct_cvpr2016_v2.lst
val_batch_size: 12
val_num_of_workers: 10
val_shuffle_data: false
weight_decay: 0.00001
