dataset_path: "./datasets/nvGesture"
train_annotation_path: "./datasets/nvGesture/nvgesture_train_correct_cvpr2016_v2.lst"
val_annotation_path: "./datasets/nvGesture/nvgesture_test_correct_cvpr2016_v2.lst"
rgb_ckp_model_path: "./training_outputs/unimodal_rgb_5_2/2022-11-15T11:47/model/model_rgb_19.pt"
depth_ckp_model_path: "./training_outputs/unimodal_depth_1/2022-11-28T08:33/model/DEPTH_best.pt"

network: "DETECTOR"  # "DETECTOR" "CLASSIFIER"
modalities: ["RGB"]  # "RGB", "DEPTH"
epoch: 100
learning_rate: 0.0001
lambda: 0.0005  # 50 x 10^-3
dropout_prob: 0
weight_decay: 0.00001
tb_batch_freq: 100

# early stop parameters
patience: 16
delta: 0

img_x: 224
img_y: 224
depth_x: 224
depth_y: 224

# dataset parameters
sample_duration: 16  # 64
frame_jump: 2
cover_ratio: 0.5
used_classes: [10, 14, 20, 22, 24]

train_batch_size: 4
train_shuffle_data: True
train_num_of_workers: 10

val_batch_size: 4
val_shuffle_data: False
val_num_of_workers: 10


