cover_ratio: 0.8261346474040011
dataset_path: ./datasets/nvGesture
depth_ckp_model_path: null
depth_x: 224
depth_y: 224
dropout_prob: 0.47134464201883364
epoch: 100
frame_jump: 3
img_x: 224
img_y: 224
lambda: 0.05
learning_rate: 0.0001
only_with_gesture: true
rgb_ckp_model_path: null
sample_duration: 70
tb_batch_freq: 100
train_annotation_path: ./datasets/nvGesture/nvgesture_train_correct_cvpr2016_v2.lst
train_batch_size: 7
train_num_of_workers: 10
train_shuffle_data: true
used_classes: [10, 14, 20, 22, 24]
val_annotation_path: ./datasets/nvGesture/nvgesture_test_correct_cvpr2016_v2.lst
val_batch_size: 7
val_num_of_workers: 10
val_shuffle_data: false
weight_decay: 0.0001
